### ISSUE TITLE
Differences with Open Audio Analytics?

### ISSUE THREAD

**Issue by kookster** [backtracks/open-podcast-analytics#1]
A brief look shows they are similar, is there a description of the differences?

**Comment by jgill333** [comment]
@kookster,
There is no an explicit listing of the differences...yet. 

[`Open Podcast Analytics (OPA)`](https://github.com/backtracks/open-podcast-analytics) is, as the name gives away, geared specifically towards podcast analytics and extends [`Open Audio Analytics (OAA)`](https://github.com/backtracks/open-audio-analytics) with a specific set of known types and properties that are specific to podcasting. This provides a base level of data to enable functionality for podcast analytics (applications, clients, and publishers as well as analytics providers can expect to have a certain baseline of data). Concepts like `season`, `series`, `episode` can be more important to podcasts along with `categories`, `subscribe`/`unsubscribe` semantics than for music purposes for example. It is a more defined extension, that may become more opinionated, that builds on [`Open Audio Analytics (OAA)`](https://github.com/backtracks/open-audio-analytics).

[`Open Audio Analytics (OAA)`](https://github.com/backtracks/open-audio-analytics) is a general purpose audio analytics spec that works for audio of all types, but it does not presume too much about the type of audio. [`OAA`](https://github.com/backtracks/open-audio-analytics) can handle music, audiobooks, podcasts, spoken word, etc. but it is purposefully very open to enable that flexibility.

**Comment by kookster** [comment]
In regards to that, seems like those additional values would be valid but option `props`, why do you need a new standard for that? Seems like it's hard enough to get one standard adopted, you want to try and promote and support two?

**Comment by jgill333** [comment]
@kookster It's really more about adoption and usage and perhaps we're wrong, but trying to communicate that something implements the *Open Podcast Analytics guideline of the Open Audio Analytics spec/protocol* makes it more difficult to communicate (even though that phrase is relatively clear in its meaning).

In terms of timeline we created tools and systems that revolved around [`OAA`](https://github.com/backtracks/open-audio-analytics) first then even internally got tired of explaining what different set of properties and uses podcasts have than music for example. It would have been odd for us to create [`OPA`](https://github.com/backtracks/open-podcast-analytics) then dervive [`OAA`](https://github.com/backtracks/open-audio-analytics) from that just in terms of the history and that it started as an offshoot of things that deal with audio analytics in general.

We're also coming from the standpoint of an audio analytics provider, regardless of type of audio.  We think there is indeed a clearer immediate need and use case for podcast analytics that can be provider agnostic in the data vs. dealing with something like the music industry exclusively. As you pointed out everything you can do with [`Open Podcast Analytics (OPA)`](https://github.com/backtracks/open-podcast-analytics) you can do with [`Open Audio Analytics (OAA)`](https://github.com/backtracks/open-audio-analytics)...but that may not always be the case. Even new things have a bit of history. 

Also as you can tell, we're focusing on the adoption of [`Open Podcast Analytics (OPA)`](https://github.com/backtracks/open-podcast-analytics) first as that's where the need is.

**Comment by jgill333** [comment]
@kookster Think there was a misunderstanding on my part relating to your question, which may have been more related to the usage of `props`. Usage of `props` is up for debate, but it's our way of avoiding too much namespacing or reserved property names by allowing and isolating custom properties from the app/client/publisher perspective to be within `props` and the top level properties (or their children) are more fixed, fewer in number, and could be utilized now or appended to in the future without conflicts to apps/clients/publisher data.
